sudo: required
services:
  - docker

before_install:
  - docker build -t muhammadatef/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run muhammadatef/multi-docker npm run test -- --coverage

after_success:
  - docker build -t muhammadatef/multi-client ./client 
  - docker build -t muhammadatef/multi-nginx ./nginx
  - docker build -t muhammadatef/multi-server ./server
  - docker build -t muhammadatef/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push muhammadatef/multi-client
  - docker push muhammadatef/multi-nginx
  - docker push muhammadatef/multi-server
  - docker push muhammadatef/multi-worker