sudo: required
services:
  - docker

before_install:
  - docker build -t moatef/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run moatef/react-test npm test -- --coverage

after_seccess:
  - docker build -t moatef/multi-client ./client 
  - docker biuld -t moatef/multi-nginx ./nginx
  - docker build -t moatef/multi-server ./server
  - docker build -t moatef/multi-worker ./worker
  